// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXO4kzxhkfbgOjdRj88D8GkTeivUAFQ_g',
    appId: '1:610417499678:web:fdc62da04026289f35580f',
    messagingSenderId: '610417499678',
    projectId: 'my-first-android-app1609',
    authDomain: 'my-first-android-app1609.firebaseapp.com',
    storageBucket: 'my-first-android-app1609.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSTsrXMmdULEDkHOwAuzmiYOlW-kSfqCA',
    appId: '1:610417499678:android:78e01e92671dbe9435580f',
    messagingSenderId: '610417499678',
    projectId: 'my-first-android-app1609',
    storageBucket: 'my-first-android-app1609.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0-p9pK37WdvK1LgOETfVXRinpnOQnDmQ',
    appId: '1:610417499678:ios:540ab3de403cb8a735580f',
    messagingSenderId: '610417499678',
    projectId: 'my-first-android-app1609',
    storageBucket: 'my-first-android-app1609.appspot.com',
    iosClientId: '610417499678-vp75lptokovpvv5fjllnvodqh8kq6t96.apps.googleusercontent.com',
    iosBundleId: 'com.example.class260622',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0-p9pK37WdvK1LgOETfVXRinpnOQnDmQ',
    appId: '1:610417499678:ios:540ab3de403cb8a735580f',
    messagingSenderId: '610417499678',
    projectId: 'my-first-android-app1609',
    storageBucket: 'my-first-android-app1609.appspot.com',
    iosClientId: '610417499678-vp75lptokovpvv5fjllnvodqh8kq6t96.apps.googleusercontent.com',
    iosBundleId: 'com.example.class260622',
  );
}
